name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "p8pro" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: ${{ github.workspace }}/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEY64 }}
        alias: ${{ secrets.KEY }}
        keyStorePassword: ${{ secrets.KEY }}
        keyPassword: ${{ secrets.KEY }}
      env:
        BUILD_TOOLS_VERSION: "33.0.1"

    - name: Retrieve version
      run: echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 7) >> $GITHUB_ENV

    - name: Rename
      run: mv ${{ github.workspace }}/app/build/outputs/apk/release/app-release-unsigned-signed.apk ${{ github.workspace }}/app/build/outputs/apk/release/Pixelify-Google-Photos-${{ env.VERSION }}.apk

    - name: Upload built apk
      uses: actions/upload-artifact@v3
      with:
        name: Pixelify-Google-Photos-${{ env.VERSION }}
        path: ${{ github.workspace }}/app/build/outputs/apk/release/Pixelify-Google-Photos-${{ env.VERSION }}.apk
